#!/bin/ash
set -e

readonly PID_FILE="/run/clamav/clamd.pid"

[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"

# only append if present
extra_conf_arg=
[[ -f "$APP_EXTRA_CONF" ]] && extra_conf_arg="-c $APP_EXTRA_CONF"

# wait for sa-update to finish
while [[ -z "$(ls /var/lib/spamassassin)" ]]; do
  sleep 10s
done

exec /usr/sbin/amavisd -c "$APP_CONF" $extra_conf_arg -P "$PID_FILE" foreground

# vim: set ft=bash ts=2 sts=2 expandtab:

